export const phones = [
    {
        sold: false,
        index: 0,
        config: {
            cost: 49.99,
            packaging: 8.80,
            id:"hml300320-1",
            images: 4,
            image_descriptions:["front and back", "packaged", "bottom of phone", "top of phone"],
            name:"iPod Touch 5th Gen. Refurbished",
            processorspeed:"1.0 GHz",
            processortype:"Apple A5",
            onboardram:"512 MB",
            storage:"32 GB",
            display:"4″ retina display (1136 x 640, 326 ppi)",
            connectivity:"USB, wi-fi, Bluetooth",
            wireless:" 802.11n 2.4 GHz and 5 GHz",
            bluetooth:"4.0",
            osinstalled:"iOS 6.0. Max. OS upgrade: iOS 9.x).",
            dimensions:"4.86 x 2.31 x 0.24",
            weight:"3.10oz",
            battery:"Battery provides 40 hours (music), 8 hours (video)",
            color:"Product red",
            refurbs:["New home button"],
        },
    },
    {
        sold: false,
        index: 1,
        config: {
            cost: 199.50,
            packaging: 8.80,
            id:"hml200420-2",
            images: 4,
            image_descriptions:["front and back", "full accessories", "front of phone", "back of phone"],
            name:"iPhone 7 Plus Refurbished",
            processorspeed:"2.3 GHz",
            processortype:"Apple A10 Fusion",
            onboardram:"3 GB",
            storage:"32 GB",
            display:"5.5″ retina display (1080 x 1920, 401 ppi)",
            connectivity:"a/b/g/n/ac, dual-band, hotspot",
            wireless:"Wi-Fi 802.11",
            bluetooth:"4.2, A2DP, LE",
            osinstalled:"iOS 10.0.1 Max. OS upgrade: iOS 13.4).",
            dimensions:"6.23 x 3.07 x 0.29 in",
            weight:"6.63 oz",
            battery:"2900 mAh battery (11.1 Wh)",
            color:"Jet Black",
            refurbs:["Deep clean"],
        },
    },
]

export default {
    phones,
}