name: Deploy (Staging)

on:
  push:
    branches:
      - master

env:
  HEROKU_APP_NAME: "harrysrepairs-staging"
  HEROKU_EMAIL: "harryliversedge@gmail.com"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku (staging)
        uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: $HEROKU_APP_NAME #Must be unique in Heroku
          heroku_email: $HEROKU_EMAIL
          docker_build_args: |
            REACT_APP_BACKEND_URL
            NODE_ENV
        env:
          REACT_APP_BACKEND_URL: ${{secrets.STAGING_BACKEND_URL}}
          NODE_ENV: ${{secrets.STAGING_NODE_ENV}}