name: Deploy (Production)

on:
  push:
    branches:
      - test/workflow-ci-testing
      
env:
  HEROKU_APP_NAME: "harrysrepairs"
  HEROKU_EMAIL: "harryliversedge@gmail.com"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
         with:
          ref: master
      - name: Deploy to Heroku (production)
        uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: $HEROKU_APP_NAME #Must be unique in Heroku
          heroku_email: $HEROKU_EMAIL
          usedocker: true
          appdir: web
          docker_build_args: |
            NODE_ENV
            REACT_APP_BACKEND_URL
            GOOGLE_ANALYTICS_ID
        env:
          REACT_APP_BACKEND_URL: ${{secrets.PROD_BACKEND_URL}}
          NODE_ENV: ${{secrets.PROD_NODE_ENV}}
          GOOGLE_ANALYTICS_ID: ${{secrets.PROD_GOOGLE_ANALYTICS_ID}}